version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    labels:
      - "Technical Debt"
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    labels:
      - "Technical Debt"
