spring:
  application.name: @project.artifactId@

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  datasource:
    driver-class-name: ${BPMSERVER_DATASOURCE_DRIVERCLASSNAME}
  # Spring JPA
  jpa:
    database: ${BPMSERVER_DATABASE}
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

# Define the keycloak development realm here
realm: ${SSO_REALM}
keycloak:
  auth-server-url: ${SSO_BASE_URL}

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  # security config applied with digiwf-spring-security-starter (env vars SSO_ISSUER_URL, SSO_BASE_URL, SSO_REALM)

server:
  port: ${BPMSERVER_PORT}
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
info.application.name: @project.artifactId@
info.application.version: @project.version@

digiwf:
  deployment:
    targets: ${BPMSERVER_DEPLOYMENT_TARGETS:DEV, TEST, DEMO, PROCESSESTEST, PROCESSESDEMO, PROCESSESHOTFIX}
  # Required for the application to start, even though it is not used
  security:
    client-id: ${SSO_TASK_CLIENT_ID}
    client-secret: ${SSO_TASK_CLIENT_SECRET}
