version: '3'
services:
  api-gateway:
    image: nginx:latest
    ports:
      - "8095:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bpm-repo-client:
    image: flowsquad/bpm-repo-client:dev
    ports:
      - "8093:8080"
    profiles:
      - bpm-repo-client

  postgres-cocreation:
    image: postgres:13.2
    container_name: digiwf-postgres-cocreation
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cocreationdb
    ports:
      - '25439:5432'
