io:
  miranum:
    deploymentserver:
      rest:
        targets:
          local:
            bpmn: 'http://localhost:${ENGINE_SERVER_PORT}/rest/deployment/v2/'
            dmn: 'http://localhost:${ENGINE_SERVER_PORT}/rest/deployment/v2/'
            form: 'http://localhost:${ENGINE_SERVER_PORT}/rest/deployment/v2/'
            config: 'http://localhost:${ENGINE_SERVER_PORT}/rest/deployment/v2/'
